exp_name: exp_poc_DAC_pseudoSDR_snake_high_lr_snake_v5 #exp_poc_latent_mask_tanh_v1
overfit: false


num_epochs: 400
warmup_steps: 2000
num_codebooks: 8

# add_si_sdr_loss: true
# add_si_sdr_loss_every_codebook: true
add_latent_loss: false

after_quant: false # for use_descript: true always false
use_descript: true

variable_len_ref: false
variable_len_train: false

lr: 5.0e-4
weight_decay: 0.00001


train:
  cut_len: 48000 #144000
  batch_size: 64 #96

val:  
  cut_len: 48000 #144000
  batch_size: 192
